/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLayout: typeof import('./src/components/AppLayout.vue')['default']
    Apps: typeof import('./src/components/Sidebar/Apps.vue')['default']
    AppSidebar: typeof import('./src/components/Sidebar/AppSidebar.vue')['default']
    PortalLogo: typeof import('./src/components/Icons/PortalLogo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarLink: typeof import('./src/components/Sidebar/SidebarLink.vue')['default']
    UserDropdown: typeof import('./src/components/Sidebar/UserDropdown.vue')['default']
  }
}
